"""Training-base primitives for large-model CFIE training."""

from cfie_training.training_base.activation_checkpoint import (
    ActivationCheckpointPlanner,
    ActivationCheckpointPolicy,
    ActivationPeakEstimator,
    CheckpointSegment,
    SegmentGradEstimator,
)
from cfie_training.training_base.adam_state_store import (
    AdamStateShardRecord,
    CpuAdamFp8StateStore,
    state_key,
)
from cfie_training.training_base.adam_update import (
    AdamWConfig,
    BlockFp8StateCodec,
    CpuAdamFp8Updater,
    CpuAdamParamUpdate,
    CpuAdamWindowUpdate,
    adam_state_num_bytes,
)
from cfie_training.training_base.checkpoint_import import (
    CheckpointImportPlan,
    CheckpointStoreInitResult,
    ImportedCheckpointParam,
    Qwen35MoeCheckpointImportConfig,
    Qwen35MoeCheckpointImporter,
    import_qwen35_moe_checkpoint,
    import_qwen35_moe_checkpoint_to_fp32_store,
    initialize_fp32_store_from_import_plan,
    qwen35_moe_checkpoint_key_filter,
)
from cfie_training.training_base.checkpoint_io import (
    CheckpointTensorLoadStats,
    iter_checkpoint_tensors,
)
from cfie_training.training_base.capacity_planning import (
    TrainingBaseCapacityReport,
    bytes_to_gib,
    capacity_report_from_manifest,
    estimate_qwen35_moe_capacity,
)
from cfie_training.training_base.fp32_shard_store import (
    FP32ShardStore,
    ParamShardRecord,
)
from cfie_training.training_base.gptq_cache_store import (
    GptqCacheRecord,
    GptqCacheStore,
)
from cfie_training.training_base.gptq_checkpoint import (
    GptqInt4CheckpointDecoder,
    GptqInt4CheckpointTensors,
    pack_gptq_int4_qweight,
    pack_gptq_int4_qzeros,
    unpack_gptq_int4_qweight,
    unpack_gptq_int4_qzeros,
)
from cfie_training.training_base.gptq_marlin_bundle import (
    DecodedGptqMarlinBundle,
    GptqMarlinBundleCodec,
    GptqMarlinBundleMetadata,
    GptqMarlinBundleSection,
    GptqMarlinBundleTensors,
    decode_gptq_marlin_bundle,
    encode_gptq_marlin_bundle_sections,
    gptq_marlin_bundle_layout_hash,
)
from cfie_training.training_base.gptq_requant import (
    GptqCacheRequantizer,
    GptqMarlinBundleRequantizer,
    SymmetricInt4GptqCodec,
    SymmetricInt4GptqLayout,
    gptq_bundle_num_bytes,
    gptq_layout_hash,
)
from cfie_training.training_base.gradient_window import (
    ForwardShadowStore,
    GptqUpdateBuilder,
    GradientBucket,
    GradientBucketRing,
    HotParamTrainingWindow,
    HotParamWindowUpdateSummary,
)
from cfie_training.training_base.hot_set_scheduler import (
    CoverageConstraint,
    ExpertRoutingStats,
    HotSetScheduler,
    HotSetSelection,
    RoutingWindowStats,
)
from cfie_training.training_base.model_loader import (
    Qwen35RealImporter,
    Qwen35TrainingAdapter,
    Qwen35_122B_CONFIG,
    build_quick_smoke_import,
)
from cfie_training.training_base.manifest_builder import (
    ManifestShardConfig,
    Qwen35MoeManifestConfig,
    TrainingBaseManifest,
    TrainingBaseManifestBuilder,
    TrainingParamManifestSpec,
    make_qwen35_moe_manifest_specs,
)
from cfie_training.training_base.cpu_gptq_cache import (
    CpuFullGptqCache,
)
from cfie_training.training_base.gpu_gptq import (
    GpuGptqConfig,
    GpuGptqQuantizer,
)
from cfie_training.training_base.training_model import (
    Qwen35ForTraining,
    RMSNorm,
    TrainingDecoderLayer,
    TrainingFullAttention,
    TrainingGatedDeltaNet,
    TrainingQwenMoELayer,
)
from cfie_training.training_base.predictor_integration import (
    HiddenStateSummarizer,
    PredictorHotSetGuide,
)
from cfie_training.training_base.peak_monitor import (
    PeakMonitor,
    PeakTelemetryRecorder,
    ThresholdEvent,
    TorchProcessResourceSampler,
    TrainingResourcePeaks,
    TrainingResourceSampler,
    TrainingResourceSnapshot,
    TrainingResourceThresholds,
    TrainingResourceUsage,
)
from cfie_training.training_base.real_model_adapter import (
    QwenMoEExpertMLP,
    _group_expert_param_ids,
    _parse_expert_param_id,
)
from cfie_training.training_base.progress_state import (
    ProgressStateWriter,
    TrainingProgressState,
    digest_hot_set,
)
from cfie_training.training_base.resident_gptq_cache import (
    BytesResidentGptqBackend,
    ResidentGptqCache,
    ResidentGptqCacheEntry,
    ResidentGptqCacheStats,
    ResidentGptqPayloadBackend,
    TorchTensorResidentGptqBackend,
)
from cfie_training.training_base.router_prefetch import (
    ExpertBundleIds,
    RoutedExpert,
    RouterGptqPrefetchPlanner,
    RouterPrefetchDepthDecision,
    RouterPrefetchDepthTuner,
    RouterPrefetchDepthTuningConfig,
    RouterPrefetchFailure,
    RouterPrefetchPlan,
    RouterPrefetchResult,
)
from cfie_training.training_base.training_memory_planner import (
    MemoryPlan,
    MemoryProfile,
    ModelDimensions,
    TrainingMemoryPlanner,
)
from cfie_training.training_base.training_loop import (
    NoOpTrainingModel,
    TrainingDataBatchInput,
    TrainingLoop,
    TrainingLoopConfig,
    TrainingLoopStepResult,
)
from cfie_training.training_base.smoke_pipeline import (
    HotSetSwitchDecision,
    TrainingSmokePipeline,
    TrainingSmokePipelineConfig,
    TrainingSmokeStepInput,
    TrainingSmokeStepResult,
)
from cfie_training.training_base.window_commit import TrainingWindowCommitter
from cfie_training.training_base.window_plan import (
    HotSetPlan,
    TouchedParamSummary,
    TrainableParamSpec,
    TrainingWindowBudget,
    TrainingWindowPlanner,
)
from cfie_training.training_base.window_runtime import (
    CompositeTrainingWindowHooks,
    LoggingTrainingWindowHooks,
    NoOpTrainingWindowHooks,
    TrainingWindowHooks,
    TrainingWindowRuntime,
    ValidatingTrainingWindowHooks,
    WindowCommitPayload,
)

__all__ = [
    "ActivationCheckpointPlanner",
    "ActivationCheckpointPolicy",
    "ActivationPeakEstimator",
    "AdamStateShardRecord",
    "AdamWConfig",
    "BlockFp8StateCodec",
    "BytesResidentGptqBackend",
    "CheckpointImportPlan",
    "CheckpointStoreInitResult",
    "CheckpointSegment",
    "CheckpointTensorLoadStats",
    "CompositeTrainingWindowHooks",
    "CpuFullGptqCache",
    "CpuAdamFp8Updater",
    "CoverageConstraint",
    "CpuAdamFp8StateStore",
    "CpuAdamParamUpdate",
    "CpuAdamWindowUpdate",
    "DecodedGptqMarlinBundle",
    "ExpertBundleIds",
    "ExpertRoutingStats",
    "FP32ShardStore",
    "ForwardShadowStore",
    "GradientBucket",
    "GpuGptqConfig",
    "GpuGptqQuantizer",
    "GradientBucketRing",
    "GptqCacheRecord",
    "GptqCacheRequantizer",
    "GptqCacheStore",
    "GptqInt4CheckpointDecoder",
    "GptqInt4CheckpointTensors",
    "GptqMarlinBundleCodec",
    "GptqMarlinBundleMetadata",
    "GptqMarlinBundleRequantizer",
    "GptqMarlinBundleSection",
    "GptqMarlinBundleTensors",
    "GptqUpdateBuilder",
    "HiddenStateSummarizer",
    "HotParamTrainingWindow",
    "HotParamWindowUpdateSummary",
    "HotSetPlan",
    "HotSetScheduler",
    "HotSetSelection",
    "HotSetSwitchDecision",
    "ImportedCheckpointParam",
    "LoggingTrainingWindowHooks",
    "ManifestShardConfig",
    "MemoryPlan",
    "MemoryProfile",
    "ModelDimensions",
    "NoOpTrainingModel",
    "NoOpTrainingWindowHooks",
    "ParamShardRecord",
    "PeakMonitor",
    "PeakTelemetryRecorder",
    "ProgressStateWriter",
    "Qwen35MoeCheckpointImportConfig",
    "Qwen35MoeCheckpointImporter",
    "Qwen35RealImporter",
    "Qwen35TrainingAdapter",
    "Qwen35_122B_CONFIG",
    "QwenMoEExpertMLP",
    "Qwen35ForTraining",
    "RMSNorm",
    "Qwen35MoeManifestConfig",
    "ResidentGptqCache",
    "ResidentGptqCacheEntry",
    "ResidentGptqCacheStats",
    "ResidentGptqPayloadBackend",
    "RoutedExpert",
    "RouterGptqPrefetchPlanner",
    "RouterPrefetchDepthDecision",
    "RouterPrefetchDepthTuner",
    "RouterPrefetchDepthTuningConfig",
    "RouterPrefetchFailure",
    "RouterPrefetchPlan",
    "RouterPrefetchResult",
    "RoutingWindowStats",
    "SegmentGradEstimator",
    "SymmetricInt4GptqCodec",
    "SymmetricInt4GptqLayout",
    "ThresholdEvent",
    "TorchProcessResourceSampler",
    "TorchTensorResidentGptqBackend",
    "TouchedParamSummary",
    "ValidatingTrainingWindowHooks",
    "TrainingBaseCapacityReport",
    "TrainableParamSpec",
    "TrainingBaseManifest",
    "TrainingBaseManifestBuilder",
    "TrainingDataBatchInput",
    "TrainingLoop",
    "TrainingLoopConfig",
    "TrainingLoopStepResult",
    "TrainingMemoryPlanner",
    "TrainingParamManifestSpec",
    "TrainingProgressState",
    "TrainingResourcePeaks",
    "TrainingResourceSampler",
    "TrainingResourceSnapshot",
    "TrainingResourceThresholds",
    "TrainingResourceUsage",
    "TrainingSmokePipeline",
    "TrainingSmokePipelineConfig",
    "TrainingSmokeStepInput",
    "TrainingSmokeStepResult",
    "TrainingWindowBudget",
    "TrainingWindowCommitter",
    "TrainingWindowHooks",
    "TrainingWindowPlanner",
    "TrainingWindowRuntime",
    "WindowCommitPayload",
    "adam_state_num_bytes",
    "build_quick_smoke_import",
    "bytes_to_gib",
    "capacity_report_from_manifest",
    "decode_gptq_marlin_bundle",
    "encode_gptq_marlin_bundle_sections",
    "digest_hot_set",
    "estimate_qwen35_moe_capacity",
    "gptq_bundle_num_bytes",
    "gptq_layout_hash",
    "gptq_marlin_bundle_layout_hash",
    "import_qwen35_moe_checkpoint",
    "import_qwen35_moe_checkpoint_to_fp32_store",
    "initialize_fp32_store_from_import_plan",
    "iter_checkpoint_tensors",
    "make_qwen35_moe_manifest_specs",
    "pack_gptq_int4_qweight",
    "pack_gptq_int4_qzeros",
    "qwen35_moe_checkpoint_key_filter",
    "state_key",
    "unpack_gptq_int4_qweight",
    "unpack_gptq_int4_qzeros",
]
