# SPDX-License-Identifier: Apache-2.0
"""Normalize model-native text tool calls into Responses output items."""

from __future__ import annotations

import json
import re
from typing import Any

from openai.types.responses import (
    ResponseFunctionToolCall,
    ResponseOutputItem,
    ResponseOutputMessage,
    ResponseOutputText,
)

from cfie.utils import random_uuid

_TOOL_BLOCK_RE = re.compile(
    r"<tool_call\b[^>]*>(.*?)</tool_call>",
    flags=re.IGNORECASE | re.DOTALL,
)
_TOOL_CODE_BLOCK_RE = re.compile(
    r"<tool_code\b[^>]*>(.*?)</tool_code>",
    flags=re.IGNORECASE | re.DOTALL,
)
_FUNCTION_RE = re.compile(
    r"<function=([A-Za-z_][A-Za-z0-9_]*)>(.*?)</function>",
    flags=re.IGNORECASE | re.DOTALL,
)
_PARAMETER_RE = re.compile(
    r"<parameter=([A-Za-z_][A-Za-z0-9_]*)>(.*?)</parameter>",
    flags=re.IGNORECASE | re.DOTALL,
)


def normalize_text_tool_calls_in_response_outputs(
    output: list[ResponseOutputItem],
) -> list[ResponseOutputItem]:
    """Split Qwen-style text tool calls out of Response message text.

    Qwen/Qwen3 XML-style tool calling is generated by the model as ordinary
    text tokens. The Responses API should expose those calls as structured
    ``function_call`` output items, while leaving only user-visible prose in
    ``output_text``.
    """

    normalized: list[ResponseOutputItem] = []
    generated_calls: list[ResponseFunctionToolCall] = []
    for item in output:
        stripped_item, calls = _normalize_output_item(item)
        if stripped_item is not None:
            normalized.append(stripped_item)
        generated_calls.extend(calls)

    if not generated_calls:
        return output

    seen = {
        _function_call_signature(item)
        for item in normalized
        if _item_type(item) == "function_call"
    }
    for call in generated_calls:
        signature = _function_call_signature(call)
        if signature in seen:
            continue
        normalized.append(call)
        seen.add(signature)
    return normalized


def _normalize_output_item(
    item: ResponseOutputItem,
) -> tuple[ResponseOutputItem | None, list[ResponseFunctionToolCall]]:
    if _item_type(item) != "message":
        return item, []
    content = getattr(item, "content", None)
    if not isinstance(content, list):
        return item, []

    normalized_parts: list[Any] = []
    calls: list[ResponseFunctionToolCall] = []
    changed = False
    for part in content:
        part_type = _item_type(part)
        text = getattr(part, "text", None)
        if part_type not in {"output_text", "text"} or not isinstance(text, str):
            normalized_parts.append(part)
            continue

        parsed_calls = _parse_qwen_xml_tool_calls(text)
        cleaned = _strip_qwen_tool_call_blocks(text)
        if parsed_calls:
            calls.extend(parsed_calls)
            changed = True
        if cleaned:
            normalized_parts.append(
                ResponseOutputText(
                    text=cleaned,
                    annotations=getattr(part, "annotations", []) or [],
                    type="output_text",
                    # The original logprobs no longer align after stripping tool
                    # syntax, so do not expose misleading per-character logprobs.
                    logprobs=None if cleaned != text else getattr(part, "logprobs", None),
                )
            )
        elif not parsed_calls:
            normalized_parts.append(part)

    if not changed:
        return item, []
    if not normalized_parts:
        return None, calls
    return (
        ResponseOutputMessage(
            id=getattr(item, "id", None) or f"msg_{random_uuid()}",
            content=normalized_parts,
            role=getattr(item, "role", "assistant"),
            status=getattr(item, "status", "completed"),
            type="message",
        ),
        calls,
    )


def _parse_qwen_xml_tool_calls(text: str) -> list[ResponseFunctionToolCall]:
    calls: list[ResponseFunctionToolCall] = []
    for block in _TOOL_BLOCK_RE.findall(text):
        for name, body in _FUNCTION_RE.findall(block):
            arguments = _parse_qwen_xml_arguments(body)
            calls.append(
                ResponseFunctionToolCall(
                    id=f"fc_{random_uuid()}",
                    call_id=f"call_{random_uuid()}",
                    type="function_call",
                    status="completed",
                    name=name.strip(),
                    arguments=json.dumps(arguments, ensure_ascii=False),
                )
            )
    return calls


def _parse_qwen_xml_arguments(body: str) -> dict[str, Any]:
    arguments: dict[str, Any] = {}
    for param_name, raw_value in _PARAMETER_RE.findall(body):
        arguments[param_name.strip()] = _parse_parameter_value(raw_value)
    return arguments


def _parse_parameter_value(raw_value: str) -> Any:
    stripped = raw_value.strip()
    if not stripped:
        return ""
    if stripped[0] in "[{":
        for candidate in dict.fromkeys(
            (stripped, _repair_missing_y_coordinate(stripped))
        ):
            try:
                return json.loads(candidate)
            except json.JSONDecodeError:
                pass
    return stripped


def _repair_missing_y_coordinate(value: str) -> str:
    return re.sub(
        r'("x"\s*:\s*-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)',
        r'\1, "y": \2',
        value,
    )


def _strip_qwen_tool_call_blocks(text: str) -> str:
    text = _TOOL_BLOCK_RE.sub("", text)
    text = _TOOL_CODE_BLOCK_RE.sub("", text)
    return text.strip()


def _item_type(item: Any) -> str:
    if isinstance(item, dict):
        return str(item.get("type") or "")
    return str(getattr(item, "type", "") or "")


def _function_call_signature(item: Any) -> tuple[str, str]:
    name = item.get("name") if isinstance(item, dict) else getattr(item, "name", "")
    args = (
        item.get("arguments")
        if isinstance(item, dict)
        else getattr(item, "arguments", "")
    )
    if not isinstance(args, str):
        args = json.dumps(args, ensure_ascii=False, sort_keys=True)
    return (str(name), args)
